"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
${imports if imports else ""}
revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    # Review autogenerated code. RLS, grants, functions, triggers, exclusion constraints and
    # partitions are not autogenerated: add them here with op.execute().
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    raise RuntimeError("Migrations are forward-only; ship a new revision instead.")
