"""IAM, tenancy and audit: tables, scope helpers, RLS, append-only audit, partitions.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 21:56:05.328314
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Hand-written (not autogenerated). Frozen here: never import application code.
SCOPE_FUNCTIONS = """
CREATE FUNCTION iam.current_user_id() RETURNS uuid LANGUAGE sql STABLE AS
$$ SELECT nullif(pg_catalog.current_setting('app.user_id', true), '')::uuid $$;
CREATE FUNCTION tenancy.current_organization_id() RETURNS uuid LANGUAGE sql STABLE AS
$$ SELECT nullif(pg_catalog.current_setting('app.organization_id', true), '')::uuid $$;
CREATE FUNCTION tenancy.current_workspace_id() RETURNS uuid LANGUAGE sql STABLE AS
$$ SELECT nullif(pg_catalog.current_setting('app.workspace_id', true), '')::uuid $$;
CREATE FUNCTION iam.is_platform_admin() RETURNS boolean LANGUAGE sql STABLE AS
$$ SELECT EXISTS (SELECT 1 FROM iam.platform_admins WHERE user_id = iam.current_user_id()) $$;
CREATE FUNCTION ops.reject_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '%.% is append-only', TG_TABLE_SCHEMA, TG_TABLE_NAME
        USING ERRCODE = 'insufficient_privilege';
END $$;
"""

# The identity being resolved during login (set only after the provider verified it).
_VERIFIED_IDENTITY = (
    "provider = pg_catalog.current_setting('app.identity_provider', true) "
    "AND provider_subject = pg_catalog.current_setting('app.identity_subject', true)"
)

POLICIES = f"""
ALTER TABLE tenancy.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenancy.organizations FORCE ROW LEVEL SECURITY;
CREATE POLICY organizations_read ON tenancy.organizations FOR SELECT USING (
    id = tenancy.current_organization_id() OR iam.is_platform_admin()
    OR EXISTS (SELECT 1 FROM iam.memberships m WHERE m.organization_id = organizations.id
               AND m.user_id = iam.current_user_id() AND m.status = 'active'));
CREATE POLICY organizations_create ON tenancy.organizations FOR INSERT
    WITH CHECK (iam.is_platform_admin());
CREATE POLICY organizations_update ON tenancy.organizations FOR UPDATE
    USING (id = tenancy.current_organization_id())
    WITH CHECK (id = tenancy.current_organization_id());

ALTER TABLE tenancy.workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenancy.workspaces FORCE ROW LEVEL SECURITY;
CREATE POLICY workspaces_read ON tenancy.workspaces FOR SELECT USING (
    organization_id = tenancy.current_organization_id()
    OR id = tenancy.current_workspace_id() OR iam.is_platform_admin()
    OR EXISTS (SELECT 1 FROM iam.memberships m WHERE m.user_id = iam.current_user_id()
               AND m.status = 'active' AND m.organization_id = workspaces.organization_id
               AND (m.workspace_id IS NULL OR m.workspace_id = workspaces.id)));
CREATE POLICY workspaces_create ON tenancy.workspaces FOR INSERT WITH CHECK (
    organization_id = tenancy.current_organization_id() OR iam.is_platform_admin());
CREATE POLICY workspaces_update ON tenancy.workspaces FOR UPDATE
    USING (organization_id = tenancy.current_organization_id()
           OR id = tenancy.current_workspace_id())
    WITH CHECK (organization_id = tenancy.current_organization_id()
                OR id = tenancy.current_workspace_id());

ALTER TABLE iam.memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.memberships FORCE ROW LEVEL SECURITY;
CREATE POLICY memberships_read ON iam.memberships FOR SELECT USING (
    user_id = iam.current_user_id()
    OR organization_id = tenancy.current_organization_id() OR iam.is_platform_admin());
CREATE POLICY memberships_create ON iam.memberships FOR INSERT WITH CHECK (
    organization_id = tenancy.current_organization_id() OR iam.is_platform_admin());
CREATE POLICY memberships_update ON iam.memberships FOR UPDATE
    USING (organization_id = tenancy.current_organization_id() OR iam.is_platform_admin())
    WITH CHECK (organization_id = tenancy.current_organization_id() OR iam.is_platform_admin());

ALTER TABLE iam.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.users FORCE ROW LEVEL SECURITY;
CREATE POLICY users_read ON iam.users FOR SELECT USING (
    id = iam.current_user_id() OR iam.is_platform_admin()
    OR EXISTS (SELECT 1 FROM iam.identities i WHERE i.user_id = users.id)
    -- first login of an invited user: the provider verified this exact email
    OR email = pg_catalog.current_setting('app.identity_email', true)
    OR EXISTS (SELECT 1 FROM iam.memberships m WHERE m.user_id = users.id
               AND m.organization_id = tenancy.current_organization_id()));
CREATE POLICY users_create ON iam.users FOR INSERT WITH CHECK (true);
CREATE POLICY users_update ON iam.users FOR UPDATE
    USING (id = iam.current_user_id() OR iam.is_platform_admin())
    WITH CHECK (id = iam.current_user_id() OR iam.is_platform_admin());

ALTER TABLE iam.identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.identities FORCE ROW LEVEL SECURITY;
CREATE POLICY identities_read ON iam.identities FOR SELECT USING (
    user_id = iam.current_user_id() OR iam.is_platform_admin() OR ({_VERIFIED_IDENTITY}));
CREATE POLICY identities_link ON iam.identities FOR INSERT WITH CHECK ({_VERIFIED_IDENTITY});
CREATE POLICY identities_touch ON iam.identities FOR UPDATE
    USING (user_id = iam.current_user_id() OR ({_VERIFIED_IDENTITY}))
    WITH CHECK (user_id = iam.current_user_id() OR ({_VERIFIED_IDENTITY}));

ALTER TABLE iam.api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE iam.api_keys FORCE ROW LEVEL SECURITY;
CREATE POLICY api_keys_read ON iam.api_keys FOR SELECT USING (
    organization_id = tenancy.current_organization_id()
    OR key_hash = pg_catalog.current_setting('app.api_key_hash', true));
CREATE POLICY api_keys_create ON iam.api_keys FOR INSERT
    WITH CHECK (organization_id = tenancy.current_organization_id());
CREATE POLICY api_keys_update ON iam.api_keys FOR UPDATE
    USING (organization_id = tenancy.current_organization_id()
           OR key_hash = pg_catalog.current_setting('app.api_key_hash', true))
    WITH CHECK (organization_id = tenancy.current_organization_id()
                OR key_hash = pg_catalog.current_setting('app.api_key_hash', true));

-- Owner-managed platform table: the application may only read its own row (not FORCE).
ALTER TABLE iam.platform_admins ENABLE ROW LEVEL SECURITY;
CREATE POLICY platform_admins_self ON iam.platform_admins FOR SELECT
    USING (user_id = iam.current_user_id());

ALTER TABLE audit.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit.audit_log FORCE ROW LEVEL SECURITY;
CREATE POLICY audit_read ON audit.audit_log FOR SELECT
    USING (organization_id = tenancy.current_organization_id());
CREATE POLICY audit_append ON audit.audit_log FOR INSERT WITH CHECK (
    organization_id = tenancy.current_organization_id() OR iam.is_platform_admin());
CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON audit.audit_log
    FOR EACH ROW EXECUTE FUNCTION ops.reject_mutation();
"""

# Monthly UTC partitions. Partitions get RLS with no policy: only the parent is readable.
PARTITIONS = """
CREATE FUNCTION audit.ensure_partitions(months_ahead integer DEFAULT 2) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
    first_month timestamp := date_trunc('month', now() AT TIME ZONE 'UTC');
    month_start timestamp;
    partition_name text;
BEGIN
    FOR i IN 0..months_ahead LOOP
        month_start := first_month + make_interval(months => i);
        partition_name := 'audit_log_p' || to_char(month_start, 'YYYYMM');
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS audit.%I PARTITION OF audit.audit_log '
            'FOR VALUES FROM (%L) TO (%L)',
            partition_name,
            month_start AT TIME ZONE 'UTC',
            (month_start + interval '1 month') AT TIME ZONE 'UTC');
        EXECUTE format('ALTER TABLE audit.%I ENABLE ROW LEVEL SECURITY', partition_name);
        EXECUTE format('ALTER TABLE audit.%I FORCE ROW LEVEL SECURITY', partition_name);
    END LOOP;
END $$;
CREATE TABLE audit.audit_log_default PARTITION OF audit.audit_log DEFAULT;
ALTER TABLE audit.audit_log_default ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit.audit_log_default FORCE ROW LEVEL SECURITY;
SELECT audit.ensure_partitions(2);
"""


def upgrade() -> None:
    # Review autogenerated code. RLS, grants, functions, triggers, exclusion constraints and
    # partitions are not autogenerated: add them here with op.execute().
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email = lower(email) AND length(email) BETWEEN 3 AND 320 "
            "AND position('@' in email) > 1",
            name=op.f("ck_users_email_format"),
        ),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_users_status")),
        sa.CheckConstraint(
            "display_name IS NULL OR length(display_name) <= 200", name=op.f("ck_users_name_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        schema="iam",
    )
    op.create_table(
        "organizations",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("plan", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("data_region", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'", name=op.f("ck_organizations_slug_format")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'closed')", name=op.f("ck_organizations_status")
        ),
        sa.CheckConstraint(
            "length(name) BETWEEN 1 AND 200", name=op.f("ck_organizations_name_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
        schema="tenancy",
    )
    op.create_table(
        "pack_versions",
        sa.Column("pack_key", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checksum", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'available'"), nullable=False),
        sa.Column(
            "released_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('available', 'deprecated', 'withdrawn')",
            name=op.f("ck_pack_versions_status"),
        ),
        sa.PrimaryKeyConstraint("pack_key", "version", name=op.f("pk_pack_versions")),
        schema="tenancy",
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("change_diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correlation_id", sa.Text(), nullable=True),
        sa.Column("hash_chain", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "actor_type IN ('user', 'api_key', 'system', 'runtime')",
            name=op.f("ck_audit_log_actor_type"),
        ),
        sa.CheckConstraint(
            "outcome IN ('success', 'denied', 'failed')", name=op.f("ck_audit_log_outcome")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["tenancy.organizations.id"],
            name=op.f("fk_audit_log_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", "occurred_at", name=op.f("pk_audit_log")),
        schema="audit",
        postgresql_partition_by="RANGE (occurred_at)",
    )
    op.create_index(
        op.f("ix_audit_log_organization_id_occurred_at"),
        "audit_log",
        ["organization_id", "occurred_at"],
        unique=False,
        schema="audit",
    )
    op.create_index(
        op.f("ix_audit_log_workspace_id_resource_type_resource_id"),
        "audit_log",
        ["workspace_id", "resource_type", "resource_id"],
        unique=False,
        schema="audit",
    )
    op.create_table(
        "identities",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_subject", sa.Text(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["iam.users.id"], name=op.f("fk_identities_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identities")),
        sa.UniqueConstraint(
            "provider", "provider_subject", name=op.f("uq_identities_provider_provider_subject")
        ),
        schema="iam",
    )
    op.create_index(
        op.f("ix_identities_user_id"), "identities", ["user_id"], unique=False, schema="iam"
    )
    op.create_table(
        "platform_admins",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["iam.users.id"], name=op.f("fk_platform_admins_granted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["iam.users.id"], name=op.f("fk_platform_admins_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_platform_admins")),
        schema="iam",
    )
    op.create_table(
        "workspaces",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("industry", sa.Text(), nullable=False),
        sa.Column("pack_key", sa.Text(), nullable=False),
        sa.Column("pack_version", sa.Text(), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("default_language", sa.Text(), nullable=False),
        sa.Column("supported_languages", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("max_call_seconds", sa.Integer(), nullable=True),
        sa.Column("monthly_minutes_limit", sa.Integer(), nullable=True),
        sa.Column(
            "recording_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'", name=op.f("ck_workspaces_slug_format")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'archived')", name=op.f("ck_workspaces_status")
        ),
        sa.CheckConstraint(
            "cardinality(supported_languages) > 0 AND default_language = ANY (supported_languages)",
            name=op.f("ck_workspaces_languages"),
        ),
        sa.CheckConstraint(
            "length(name) BETWEEN 1 AND 200", name=op.f("ck_workspaces_name_length")
        ),
        sa.CheckConstraint(
            "max_call_seconds IS NULL OR max_call_seconds > 0", name=op.f("ck_workspaces_max_call")
        ),
        sa.CheckConstraint(
            "monthly_minutes_limit IS NULL OR monthly_minutes_limit >= 0",
            name=op.f("ck_workspaces_minutes"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["tenancy.organizations.id"],
            name=op.f("fk_workspaces_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["pack_key", "pack_version"],
            ["tenancy.pack_versions.pack_key", "tenancy.pack_versions.version"],
            name=op.f("fk_workspaces_pack_key_pack_version_pack_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_workspaces_organization_id_id")),
        sa.UniqueConstraint(
            "organization_id", "slug", name=op.f("uq_workspaces_organization_id_slug")
        ),
        schema="tenancy",
    )
    op.create_index(
        op.f("ix_workspaces_organization_id"),
        "workspaces",
        ["organization_id"],
        unique=False,
        schema="tenancy",
    )
    op.create_table(
        "api_keys",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key_prefix", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("scopes", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("key_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_api_keys_key_hash_format")),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 150", name=op.f("ck_api_keys_name_length")),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["tenancy.workspaces.organization_id", "tenancy.workspaces.id"],
            name=op.f("fk_api_keys_organization_id_workspace_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["tenancy.organizations.id"],
            name=op.f("fk_api_keys_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
        schema="iam",
    )
    op.create_index(
        op.f("ix_api_keys_organization_id"),
        "api_keys",
        ["organization_id"],
        unique=False,
        schema="iam",
    )
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'manager', 'staff', 'viewer')",
            name=op.f("ck_memberships_role"),
        ),
        sa.CheckConstraint(
            "role NOT IN ('owner', 'admin') OR workspace_id IS NULL",
            name=op.f("ck_memberships_org_wide_roles"),
        ),
        sa.CheckConstraint(
            "status IN ('invited', 'active', 'suspended', 'revoked')",
            name=op.f("ck_memberships_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id"],
            ["tenancy.workspaces.organization_id", "tenancy.workspaces.id"],
            name=op.f("fk_memberships_organization_id_workspace_id_workspaces"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["tenancy.organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["iam.users.id"], name=op.f("fk_memberships_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        schema="iam",
    )
    op.create_index(
        op.f("ix_memberships_organization_id"),
        "memberships",
        ["organization_id"],
        unique=False,
        schema="iam",
    )
    op.create_index(
        op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False, schema="iam"
    )
    op.create_index(
        op.f("ix_memberships_user_id_organization_id_workspace_id"),
        "memberships",
        ["user_id", "organization_id", "workspace_id"],
        unique=True,
        schema="iam",
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        op.f("ix_memberships_workspace_id"),
        "memberships",
        ["workspace_id"],
        unique=False,
        schema="iam",
    )
    # ### end Alembic commands ###

    op.execute(SCOPE_FUNCTIONS)
    op.execute(POLICIES)
    op.execute(PARTITIONS)


def downgrade() -> None:
    raise RuntimeError("Migrations are forward-only; ship a new revision instead.")
