"""Agents and catalog: tables, tenant RLS, ingress lookup, relation exclusion, name search.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 23:14:32.823640
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Hand-written (not autogenerated). Frozen here: never import application code.
TENANT_TABLES = (
    "agents.agents",
    "agents.phone_numbers",
    "agents.agent_tools",
    "catalog.entity_types",
    "catalog.entities",
    "catalog.entity_relations",
    "catalog.availability_rules",
    "catalog.availability_exceptions",
)
_IN_WORKSPACE = "workspace_id = tenancy.current_workspace_id()"


def _tenant_policies(table: str) -> str:
    """Workspace-scoped read/insert/update. No DELETE policy: rows are soft-deleted."""
    name = table.split(".")[1]
    return f"""
ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
CREATE POLICY {name}_read ON {table} FOR SELECT USING ({_IN_WORKSPACE});
CREATE POLICY {name}_create ON {table} FOR INSERT WITH CHECK ({_IN_WORKSPACE});
CREATE POLICY {name}_update ON {table} FOR UPDATE
    USING ({_IN_WORKSPACE}) WITH CHECK ({_IN_WORKSPACE});
"""


# Incoming call, before any tenant is known: the runtime may read exactly the active number
# the caller dialled (set by trusted telephony ingress), to find its agent and workspace.
INGRESS = """
CREATE POLICY phone_numbers_ingress ON agents.phone_numbers FOR SELECT USING (
    status = 'active'
    AND phone_number = pg_catalog.current_setting('app.called_number', true));
"""

# No two live relations of the same type between the same entities with overlapping validity.
RELATION_EXCLUSION = """
ALTER TABLE catalog.entity_relations ADD CONSTRAINT ex_entity_relations_no_overlap
EXCLUDE USING gist (
    workspace_id WITH =,
    from_entity_id WITH =,
    to_entity_id WITH =,
    relation_type WITH =,
    coalesce(valid_during, '(,)'::tstzrange) WITH &&
) WHERE (deleted_at IS NULL);
"""


def upgrade() -> None:
    # Review autogenerated code. RLS, grants, functions, triggers, exclusion constraints and
    # partitions are not autogenerated: add them here with op.execute().
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("persona", sa.Text(), nullable=True),
        sa.Column("prompt_template_key", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("stt_provider", sa.Text(), nullable=True),
        sa.Column("stt_model", sa.Text(), nullable=True),
        sa.Column("stt_language", sa.Text(), nullable=True),
        sa.Column("llm_provider", sa.Text(), nullable=True),
        sa.Column("llm_model", sa.Text(), nullable=True),
        sa.Column("tts_provider", sa.Text(), nullable=True),
        sa.Column("tts_model", sa.Text(), nullable=True),
        sa.Column("tts_language", sa.Text(), nullable=True),
        sa.Column("greeting_message", sa.Text(), nullable=False),
        sa.Column("emergency_message", sa.Text(), nullable=False),
        sa.Column("fallback_message", sa.Text(), nullable=False),
        sa.Column(
            "transfer_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("transfer_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'", name=op.f("ck_agents_slug_format")
        ),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_agents_status")),
        sa.CheckConstraint(
            "length(greeting_message) BETWEEN 1 AND 2000 AND length(emergency_message) BETWEEN 1"
            " AND 2000 AND length(fallback_message) BETWEEN 1 AND 2000",
            name=op.f("ck_agents_messages"),
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 150", name=op.f("ck_agents_name_length")),
        sa.CheckConstraint("prompt_version >= 1", name=op.f("ck_agents_prompt_version")),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_agents_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_agents_workspace_id_id")),
        sa.UniqueConstraint("workspace_id", "slug", name=op.f("uq_agents_workspace_id_slug")),
        schema="agents",
    )
    op.create_table(
        "entity_types",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("attributes_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "searchable_fields", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("display_template", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.Text(), server_default=sa.text("'pack'"), nullable=False),
        sa.Column("source_pack_key", sa.Text(), nullable=True),
        sa.Column("source_pack_version", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "key ~ '^[a-z][a-z0-9_]{1,62}$'", name=op.f("ck_entity_types_key_format")
        ),
        sa.CheckConstraint("source IN ('pack', 'custom')", name=op.f("ck_entity_types_source")),
        sa.CheckConstraint(
            "status IN ('active', 'deprecated')", name=op.f("ck_entity_types_status")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_entity_types_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_types")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_entity_types_workspace_id_id")),
        sa.UniqueConstraint(
            "workspace_id",
            "key",
            "schema_version",
            name=op.f("uq_entity_types_workspace_id_key_schema_version"),
        ),
        schema="catalog",
    )
    op.create_table(
        "agent_tools",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("tool_key", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "agent_id"],
            ["agents.agents.workspace_id", "agents.agents.id"],
            name=op.f("fk_agent_tools_workspace_id_agent_id_agents"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_agent_tools_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_tools")),
        sa.UniqueConstraint("agent_id", "tool_key", name=op.f("uq_agent_tools_agent_id_tool_key")),
        schema="agents",
    )
    op.create_table(
        "phone_numbers",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("phone_number", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("trusted_trunk_id", sa.Text(), nullable=True),
        sa.Column("direction", sa.Text(), server_default=sa.text("'inbound'"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('inbound', 'outbound')", name=op.f("ck_phone_numbers_direction")
        ),
        sa.CheckConstraint(
            "phone_number ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f("ck_phone_numbers_e164")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'released')", name=op.f("ck_phone_numbers_status")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "agent_id"],
            ["agents.agents.workspace_id", "agents.agents.id"],
            name=op.f("fk_phone_numbers_workspace_id_agent_id_agents"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_phone_numbers_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phone_numbers")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_phone_numbers_workspace_id_id")),
        schema="agents",
    )
    op.create_index(
        op.f("ix_phone_numbers_agent_id"),
        "phone_numbers",
        ["agent_id"],
        unique=False,
        schema="agents",
    )
    op.create_index(
        op.f("ix_phone_numbers_phone_number"),
        "phone_numbers",
        ["phone_number"],
        unique=True,
        schema="agents",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "entities",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("entity_type_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("aliases", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "publication_status", sa.Text(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column("valid_during", postgresql.TSTZRANGE(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(attributes) = 'object'", name=op.f("ck_entities_attributes_object")
        ),
        sa.CheckConstraint(
            "key ~ '^[a-z0-9][a-z0-9-]{0,149}$'", name=op.f("ck_entities_key_format")
        ),
        sa.CheckConstraint(
            "publication_status IN ('draft', 'published', 'archived')",
            name=op.f("ck_entities_publication_status"),
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 200", name=op.f("ck_entities_name_length")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "entity_type_id"],
            ["catalog.entity_types.workspace_id", "catalog.entity_types.id"],
            name=op.f("fk_entities_workspace_id_entity_type_id_entity_types"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_entities_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_entities_workspace_id_id")),
        schema="catalog",
    )
    op.create_index(
        op.f("ix_entities_workspace_id_entity_type_id_publication_status"),
        "entities",
        ["workspace_id", "entity_type_id", "publication_status"],
        unique=False,
        schema="catalog",
    )
    op.create_index(
        op.f("ix_entities_workspace_id_key"),
        "entities",
        ["workspace_id", "key"],
        unique=True,
        schema="catalog",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "availability_rules",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("location_entity_id", sa.UUID(), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("rrule", sa.Text(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("valid_during", postgresql.TSTZRANGE(), nullable=True),
        sa.Column(
            "publication_status", sa.Text(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "publication_status IN ('draft', 'published', 'archived')",
            name=op.f("ck_availability_rules_publication_status"),
        ),
        sa.CheckConstraint("end_time > start_time", name=op.f("ck_availability_rules_window")),
        sa.CheckConstraint(
            "entity_id IS NOT NULL OR location_entity_id IS NOT NULL",
            name=op.f("ck_availability_rules_has_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_availability_rules_workspace_id_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "location_entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_availability_rules_workspace_id_location_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_availability_rules_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availability_rules")),
        sa.UniqueConstraint(
            "workspace_id", "id", name=op.f("uq_availability_rules_workspace_id_id")
        ),
        schema="catalog",
    )
    op.create_index(
        op.f("ix_availability_rules_entity_id"),
        "availability_rules",
        ["entity_id"],
        unique=False,
        schema="catalog",
    )
    op.create_table(
        "entity_relations",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("from_entity_id", sa.UUID(), nullable=False),
        sa.Column("to_entity_id", sa.UUID(), nullable=False),
        sa.Column("relation_type", sa.Text(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "publication_status", sa.Text(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column("valid_during", postgresql.TSTZRANGE(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attributes IS NULL OR jsonb_typeof(attributes) = 'object'",
            name=op.f("ck_entity_relations_attributes_object"),
        ),
        sa.CheckConstraint(
            "publication_status IN ('draft', 'published', 'archived')",
            name=op.f("ck_entity_relations_publication_status"),
        ),
        sa.CheckConstraint(
            "from_entity_id <> to_entity_id", name=op.f("ck_entity_relations_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "from_entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_entity_relations_workspace_id_from_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "to_entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_entity_relations_workspace_id_to_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_entity_relations_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_relations")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_entity_relations_workspace_id_id")),
        schema="catalog",
    )
    op.create_index(
        op.f("ix_entity_relations_workspace_id_from_entity_id_relation_type"),
        "entity_relations",
        ["workspace_id", "from_entity_id", "relation_type"],
        unique=False,
        schema="catalog",
    )
    op.create_index(
        op.f("ix_entity_relations_workspace_id_to_entity_id"),
        "entity_relations",
        ["workspace_id", "to_entity_id"],
        unique=False,
        schema="catalog",
    )
    op.create_table(
        "availability_exceptions",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("availability_rule_id", sa.UUID(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("location_entity_id", sa.UUID(), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("exception_date", sa.Date(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("public_message", sa.Text(), nullable=True),
        sa.Column(
            "publication_status", sa.Text(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "publication_status IN ('draft', 'published', 'archived')",
            name=op.f("ck_availability_exceptions_publication_status"),
        ),
        sa.CheckConstraint(
            "(start_time IS NULL AND end_time IS NULL) OR (start_time IS NOT NULL"
            " AND end_time IS NOT NULL AND end_time > start_time)",
            name=op.f("ck_availability_exceptions_window"),
        ),
        sa.CheckConstraint(
            "availability_rule_id IS NOT NULL OR entity_id IS NOT NULL"
            " OR location_entity_id IS NOT NULL",
            name=op.f("ck_availability_exceptions_has_subject"),
        ),
        sa.CheckConstraint(
            "public_message IS NULL OR length(public_message) <= 500",
            name=op.f("ck_availability_exceptions_message_length"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "availability_rule_id"],
            ["catalog.availability_rules.workspace_id", "catalog.availability_rules.id"],
            name=op.f(
                "fk_availability_exceptions_workspace_id_availability_rule_id_availability_rules"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_availability_exceptions_workspace_id_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "location_entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_availability_exceptions_workspace_id_location_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_availability_exceptions_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availability_exceptions")),
        schema="catalog",
    )
    op.create_index(
        op.f("ix_availability_exceptions_entity_id"),
        "availability_exceptions",
        ["entity_id"],
        unique=False,
        schema="catalog",
    )
    op.create_index(
        "ix_entities_name_trgm",
        "entities",
        ["name"],
        unique=False,
        schema="catalog",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###

    for table in TENANT_TABLES:
        op.execute(_tenant_policies(table))
    op.execute(INGRESS)
    op.execute(RELATION_EXCLUSION)


def downgrade() -> None:
    raise RuntimeError("Migrations are forward-only; ship a new revision instead.")
