"""Knowledge: documents, versions, sections, chunks, FAQs, announcements; RLS and search.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-27 00:34:17.478472
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Hand-written (not autogenerated). Frozen here: never import application code.
TABLES = (
    "knowledge.sources",
    "knowledge.documents",
    "knowledge.document_versions",
    "knowledge.document_sections",
    "knowledge.chunks",
    "knowledge.faqs",
    "knowledge.announcements",
)
# Sections are replaced when edited and chunks rebuilt on publish: hard DELETE allowed.
DELETABLE = ("knowledge.document_sections", "knowledge.chunks")
_IN_WORKSPACE = "workspace_id = tenancy.current_workspace_id()"


def _tenant_policies(table: str) -> str:
    name = table.split(".")[1]
    sql = f"""
ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
CREATE POLICY {name}_read ON {table} FOR SELECT USING ({_IN_WORKSPACE});
CREATE POLICY {name}_create ON {table} FOR INSERT WITH CHECK ({_IN_WORKSPACE});
CREATE POLICY {name}_update ON {table} FOR UPDATE
    USING ({_IN_WORKSPACE}) WITH CHECK ({_IN_WORKSPACE});
"""
    if table in DELETABLE:
        sql += f"CREATE POLICY {name}_delete ON {table} FOR DELETE USING ({_IN_WORKSPACE});\n"
    return sql


# Lexical search (always available; Qdrant adds semantic ranking when configured).
FULL_TEXT_INDEX = """
CREATE INDEX ix_chunks_full_text ON knowledge.chunks
USING gin (to_tsvector('simple', coalesce(heading, '') || ' ' || text));
"""


def upgrade() -> None:
    # Review autogenerated code. RLS, grants, functions, triggers, exclusion constraints and
    # partitions are not autogenerated: add them here with op.execute().
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("uri", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_type IN ('upload', 'url', 'connector')", name=op.f("ck_sources_source_type")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_sources_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_sources_workspace_id_id")),
        schema="knowledge",
    )
    op.create_table(
        "documents",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("published_version_id", sa.UUID(), nullable=True),
        sa.Column("effective_during", postgresql.TSTZRANGE(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'archived')", name=op.f("ck_documents_status")),
        sa.CheckConstraint(
            "length(title) BETWEEN 1 AND 200", name=op.f("ck_documents_title_length")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "source_id"],
            ["knowledge.sources.workspace_id", "knowledge.sources.id"],
            name=op.f("fk_documents_workspace_id_source_id_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_documents_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_documents_workspace_id_id")),
        schema="knowledge",
    )
    op.create_table(
        "announcements",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("public_message", sa.Text(), nullable=False),
        sa.Column("internal_note", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("location_entity_id", sa.UUID(), nullable=True),
        sa.Column("priority", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column("valid_during", postgresql.TSTZRANGE(), nullable=False),
        sa.Column(
            "publication_status", sa.Text(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "publication_status IN ('draft', 'published', 'archived')",
            name=op.f("ck_announcements_publication_status"),
        ),
        sa.CheckConstraint("NOT isempty(valid_during)", name=op.f("ck_announcements_window")),
        sa.CheckConstraint(
            "internal_note IS NULL OR length(internal_note) <= 2000",
            name=op.f("ck_announcements_note_length"),
        ),
        sa.CheckConstraint(
            "length(public_message) BETWEEN 1 AND 2000",
            name=op.f("ck_announcements_message_length"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_announcements_workspace_id_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "location_entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_announcements_workspace_id_location_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_announcements_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_announcements_workspace_id_id")),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_announcements_workspace_id_publication_status"),
        "announcements",
        ["workspace_id", "publication_status"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "document_versions",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'needs_review'"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("checksum", sa.Text(), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=True),
        sa.Column(
            "extraction_warnings",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "checksum ~ '^[0-9a-f]{64}$'", name=op.f("ck_document_versions_checksum_format")
        ),
        sa.CheckConstraint(
            "status IN ('processing', 'needs_review', 'published', "
            "'superseded', 'rejected', 'archived')",
            name=op.f("ck_document_versions_status"),
        ),
        sa.CheckConstraint("version_no >= 1", name=op.f("ck_document_versions_version_no")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "document_id"],
            ["knowledge.documents.workspace_id", "knowledge.documents.id"],
            name=op.f("fk_document_versions_workspace_id_document_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_document_versions_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint(
            "document_id", "version_no", name=op.f("uq_document_versions_document_id_version_no")
        ),
        sa.UniqueConstraint(
            "workspace_id", "checksum", name=op.f("uq_document_versions_workspace_id_checksum")
        ),
        sa.UniqueConstraint(
            "workspace_id", "id", name=op.f("uq_document_versions_workspace_id_id")
        ),
        schema="knowledge",
    )
    op.create_table(
        "faqs",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("canonical_question", sa.Text(), nullable=False),
        sa.Column(
            "alternative_phrasings",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("approved_answer", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "publication_status", sa.Text(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column("valid_during", postgresql.TSTZRANGE(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "publication_status IN ('draft', 'published', 'archived')",
            name=op.f("ck_faqs_publication_status"),
        ),
        sa.CheckConstraint(
            "length(approved_answer) BETWEEN 1 AND 2000", name=op.f("ck_faqs_answer_length")
        ),
        sa.CheckConstraint(
            "length(canonical_question) BETWEEN 1 AND 500", name=op.f("ck_faqs_question_length")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_faqs_workspace_id_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_faqs_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faqs")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_faqs_workspace_id_id")),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_faqs_workspace_id_publication_status"),
        "faqs",
        ["workspace_id", "publication_status"],
        unique=False,
        schema="knowledge",
    )
    op.create_table(
        "document_sections",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("heading", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("keywords", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "heading IS NULL OR length(heading) <= 200",
            name=op.f("ck_document_sections_heading_length"),
        ),
        sa.CheckConstraint(
            "length(text) BETWEEN 1 AND 4000", name=op.f("ck_document_sections_text_length")
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_document_sections_position")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "document_version_id"],
            ["knowledge.document_versions.workspace_id", "knowledge.document_versions.id"],
            name=op.f("fk_document_sections_workspace_id_document_version_id_document_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_document_sections_workspace_id_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_document_sections_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_sections")),
        sa.UniqueConstraint(
            "document_version_id",
            "position",
            name=op.f("uq_document_sections_document_version_id_position"),
        ),
        sa.UniqueConstraint(
            "workspace_id", "id", name=op.f("uq_document_sections_workspace_id_id")
        ),
        schema="knowledge",
    )
    op.create_table(
        "chunks",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("heading", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("embedding_model", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "document_version_id"],
            ["knowledge.document_versions.workspace_id", "knowledge.document_versions.id"],
            name=op.f("fk_chunks_workspace_id_document_version_id_document_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_chunks_workspace_id_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "section_id"],
            ["knowledge.document_sections.workspace_id", "knowledge.document_sections.id"],
            name=op.f("fk_chunks_workspace_id_section_id_document_sections"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_chunks_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint(
            "document_version_id",
            "chunk_index",
            name=op.f("uq_chunks_document_version_id_chunk_index"),
        ),
        schema="knowledge",
    )
    op.create_index(
        op.f("ix_chunks_workspace_id_document_version_id"),
        "chunks",
        ["workspace_id", "document_version_id"],
        unique=False,
        schema="knowledge",
    )
    op.create_foreign_key(
        "fk_documents_published_version",
        "documents",
        "document_versions",
        ["workspace_id", "published_version_id"],
        ["workspace_id", "id"],
        source_schema="knowledge",
        referent_schema="knowledge",
    )
    # ### end Alembic commands ###

    for table in TABLES:
        op.execute(_tenant_policies(table))
    op.execute(FULL_TEXT_INDEX)


def downgrade() -> None:
    raise RuntimeError("Migrations are forward-only; ship a new revision instead.")
