"""Engagement (CRM): contacts, consents, conversations, call events, work items, tasks.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-27 01:03:02.258574
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Hand-written (not autogenerated). Frozen here: never import application code.
EDITABLE = (
    "engagement.contacts",
    "engagement.conversations",
    "engagement.work_item_kinds",
    "engagement.work_items",
    "engagement.tasks",
)
# History: read and insert only (no UPDATE/DELETE policy), plus a rejecting trigger.
APPEND_ONLY = ("engagement.consents", "engagement.work_item_events", "engagement.call_events")
_IN_WORKSPACE = "workspace_id = tenancy.current_workspace_id()"


def _policies(table: str) -> str:
    name = table.split(".")[1]
    sql = f"""
ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
CREATE POLICY {name}_read ON {table} FOR SELECT USING ({_IN_WORKSPACE});
CREATE POLICY {name}_create ON {table} FOR INSERT WITH CHECK ({_IN_WORKSPACE});
"""
    if table in APPEND_ONLY:
        return (
            sql
            + f"""CREATE TRIGGER {name}_append_only BEFORE UPDATE OR DELETE ON {table}
    FOR EACH ROW EXECUTE FUNCTION ops.reject_mutation();
"""
        )
    return (
        sql
        + f"""CREATE POLICY {name}_update ON {table} FOR UPDATE
    USING ({_IN_WORKSPACE}) WITH CHECK ({_IN_WORKSPACE});
"""
    )


# Monthly UTC partitions for call events; partitions have RLS with no policy.
PARTITIONS = """
CREATE FUNCTION engagement.ensure_partitions(months_ahead integer DEFAULT 2) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
    first_month timestamp := date_trunc('month', now() AT TIME ZONE 'UTC');
    month_start timestamp;
    partition_name text;
BEGIN
    FOR i IN 0..months_ahead LOOP
        month_start := first_month + make_interval(months => i);
        partition_name := 'call_events_p' || to_char(month_start, 'YYYYMM');
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS engagement.%I PARTITION OF engagement.call_events '
            'FOR VALUES FROM (%L) TO (%L)',
            partition_name,
            month_start AT TIME ZONE 'UTC',
            (month_start + interval '1 month') AT TIME ZONE 'UTC');
        EXECUTE format('ALTER TABLE engagement.%I ENABLE ROW LEVEL SECURITY', partition_name);
        EXECUTE format('ALTER TABLE engagement.%I FORCE ROW LEVEL SECURITY', partition_name);
    END LOOP;
END $$;
CREATE TABLE engagement.call_events_default PARTITION OF engagement.call_events DEFAULT;
ALTER TABLE engagement.call_events_default ENABLE ROW LEVEL SECURITY;
ALTER TABLE engagement.call_events_default FORCE ROW LEVEL SECURITY;
SELECT engagement.ensure_partitions(2);
"""


def upgrade() -> None:
    # Review autogenerated code. RLS, grants, functions, triggers, exclusion constraints and
    # partitions are not autogenerated: add them here with op.execute().
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("display_name_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("phone_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("phone_lookup_hmac", sa.Text(), nullable=True),
        sa.Column("pii_key_version", sa.Text(), nullable=True),
        sa.Column("preferred_language", sa.Text(), nullable=True),
        sa.Column("consent_status", sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pii_erased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "consent_status IN ('unknown', 'granted', 'withdrawn')",
            name=op.f("ck_contacts_consent_status"),
        ),
        sa.CheckConstraint(
            "phone_lookup_hmac IS NULL OR phone_lookup_hmac ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_contacts_lookup_format"),
        ),
        sa.CheckConstraint(
            "(display_name_ciphertext IS NULL AND phone_ciphertext IS NULL) "
            "OR pii_key_version IS NOT NULL",
            name=op.f("ck_contacts_key_version"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_contacts_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_contacts_workspace_id_id")),
        sa.UniqueConstraint(
            "workspace_id",
            "phone_lookup_hmac",
            name=op.f("uq_contacts_workspace_id_phone_lookup_hmac"),
        ),
        schema="engagement",
    )
    op.create_table(
        "work_item_kinds",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("payload_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stages", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("initial_stage", sa.Text(), nullable=False),
        sa.Column("terminal_stages", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "subject_types", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("source_pack_key", sa.Text(), nullable=True),
        sa.Column("source_pack_version", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'deprecated')", name=op.f("ck_work_item_kinds_status")
        ),
        sa.CheckConstraint(
            "initial_stage = ANY (stages)", name=op.f("ck_work_item_kinds_initial_stage")
        ),
        sa.CheckConstraint(
            "terminal_stages <@ stages", name=op.f("ck_work_item_kinds_terminal_stages")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_work_item_kinds_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_item_kinds")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_work_item_kinds_workspace_id_id")),
        sa.UniqueConstraint(
            "workspace_id",
            "key",
            "schema_version",
            name=op.f("uq_work_item_kinds_workspace_id_key_schema_version"),
        ),
        schema="engagement",
    )
    op.create_table(
        "conversations",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("agent_release_id", sa.UUID(), nullable=True),
        sa.Column("phone_number_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("channel", sa.Text(), server_default=sa.text("'voice'"), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_call_id", sa.Text(), nullable=False),
        sa.Column("provider_room_id", sa.Text(), nullable=True),
        sa.Column("caller_number_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("pii_key_version", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column(
            "detected_languages",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("primary_intent", sa.Text(), nullable=True),
        sa.Column("disposition", sa.Text(), nullable=True),
        sa.Column(
            "transfer_attempted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "transfer_succeeded", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("safety_flag", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("failure_code", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("is_test", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "channel IN ('voice', 'chat', 'whatsapp')", name=op.f("ck_conversations_channel")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'failed', 'abandoned')",
            name=op.f("ck_conversations_status"),
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_conversations_ended_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "agent_id"],
            ["agents.agents.workspace_id", "agents.agents.id"],
            name=op.f("fk_conversations_workspace_id_agent_id_agents"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "contact_id"],
            ["engagement.contacts.workspace_id", "engagement.contacts.id"],
            name=op.f("fk_conversations_workspace_id_contact_id_contacts"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "phone_number_id"],
            ["agents.phone_numbers.workspace_id", "agents.phone_numbers.id"],
            name=op.f("fk_conversations_workspace_id_phone_number_id_phone_numbers"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_conversations_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "provider", "provider_call_id", name=op.f("uq_conversations_provider_provider_call_id")
        ),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_conversations_workspace_id_id")),
        schema="engagement",
    )
    op.create_index(
        "ix_conversations_active_heartbeat",
        "conversations",
        ["heartbeat_at"],
        unique=False,
        schema="engagement",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_conversations_needing_review",
        "conversations",
        ["workspace_id", "started_at"],
        unique=False,
        schema="engagement",
        postgresql_where=sa.text("failure_code IS NOT NULL AND NOT is_test"),
    )
    op.create_index(
        op.f("ix_conversations_workspace_id_started_at"),
        "conversations",
        ["workspace_id", "started_at"],
        unique=False,
        schema="engagement",
    )
    op.create_table(
        "call_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("event_key", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column(
            "sanitized_payload",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "conversation_id"],
            ["engagement.conversations.workspace_id", "engagement.conversations.id"],
            name=op.f("fk_call_events_workspace_id_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_call_events_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", "occurred_at", name=op.f("pk_call_events")),
        sa.UniqueConstraint(
            "conversation_id",
            "event_key",
            "occurred_at",
            name=op.f("uq_call_events_conversation_id_event_key_occurred_at"),
        ),
        schema="engagement",
        postgresql_partition_by="RANGE (occurred_at)",
    )
    op.create_table(
        "consents",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("consent_type", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("notice_version", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("action IN ('granted', 'withdrawn')", name=op.f("ck_consents_action")),
        sa.CheckConstraint(
            "length(notice_version) BETWEEN 1 AND 60", name=op.f("ck_consents_notice_version")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "contact_id"],
            ["engagement.contacts.workspace_id", "engagement.contacts.id"],
            name=op.f("fk_consents_workspace_id_contact_id_contacts"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "conversation_id"],
            ["engagement.conversations.workspace_id", "engagement.conversations.id"],
            name=op.f("fk_consents_workspace_id_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_consents_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
        schema="engagement",
    )
    op.create_index(
        op.f("ix_consents_workspace_id_contact_id"),
        "consents",
        ["workspace_id", "contact_id"],
        unique=False,
        schema="engagement",
    )
    op.create_table(
        "work_items",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("kind_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("subject_name_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("callback_number_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("staff_note_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("pii_key_version", sa.Text(), nullable=True),
        sa.Column("pii_erased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assignee_user_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'", name=op.f("ck_work_items_payload_object")
        ),
        sa.CheckConstraint(
            "(subject_name_ciphertext IS NULL AND callback_number_ciphertext IS NULL "
            "AND staff_note_ciphertext IS NULL) OR pii_key_version IS NOT NULL",
            name=op.f("ck_work_items_key_version"),
        ),
        sa.CheckConstraint(
            "length(idempotency_key) BETWEEN 8 AND 200", name=op.f("ck_work_items_idempotency_key")
        ),
        sa.ForeignKeyConstraint(
            ["assignee_user_id"],
            ["iam.users.id"],
            name=op.f("fk_work_items_assignee_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "contact_id"],
            ["engagement.contacts.workspace_id", "engagement.contacts.id"],
            name=op.f("fk_work_items_workspace_id_contact_id_contacts"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "conversation_id"],
            ["engagement.conversations.workspace_id", "engagement.conversations.id"],
            name=op.f("fk_work_items_workspace_id_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "entity_id"],
            ["catalog.entities.workspace_id", "catalog.entities.id"],
            name=op.f("fk_work_items_workspace_id_entity_id_entities"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "kind_id"],
            ["engagement.work_item_kinds.workspace_id", "engagement.work_item_kinds.id"],
            name=op.f("fk_work_items_workspace_id_kind_id_work_item_kinds"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_work_items_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_items")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_work_items_workspace_id_id")),
        sa.UniqueConstraint(
            "workspace_id",
            "idempotency_key",
            name=op.f("uq_work_items_workspace_id_idempotency_key"),
        ),
        schema="engagement",
    )
    op.create_index(
        op.f("ix_work_items_workspace_id_assignee_user_id"),
        "work_items",
        ["workspace_id", "assignee_user_id"],
        unique=False,
        schema="engagement",
    )
    op.create_index(
        op.f("ix_work_items_workspace_id_entity_id"),
        "work_items",
        ["workspace_id", "entity_id"],
        unique=False,
        schema="engagement",
    )
    op.create_index(
        op.f("ix_work_items_workspace_id_stage_created_at"),
        "work_items",
        ["workspace_id", "stage", "created_at"],
        unique=False,
        schema="engagement",
    )
    op.create_table(
        "tasks",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("work_item_id", sa.UUID(), nullable=True),
        sa.Column("assignee_user_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open', 'done', 'cancelled')", name=op.f("ck_tasks_status")),
        sa.CheckConstraint(
            "description IS NULL OR length(description) <= 2000",
            name=op.f("ck_tasks_description_length"),
        ),
        sa.CheckConstraint("length(title) BETWEEN 1 AND 200", name=op.f("ck_tasks_title_length")),
        sa.ForeignKeyConstraint(
            ["assignee_user_id"], ["iam.users.id"], name=op.f("fk_tasks_assignee_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "work_item_id"],
            ["engagement.work_items.workspace_id", "engagement.work_items.id"],
            name=op.f("fk_tasks_workspace_id_work_item_id_work_items"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_tasks_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        schema="engagement",
    )
    op.create_index(
        op.f("ix_tasks_workspace_id_assignee_user_id_status"),
        "tasks",
        ["workspace_id", "assignee_user_id", "status"],
        unique=False,
        schema="engagement",
    )
    op.create_table(
        "work_item_events",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("work_item_id", sa.UUID(), nullable=False),
        sa.Column("from_stage", sa.Text(), nullable=True),
        sa.Column("to_stage", sa.Text(), nullable=True),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "metadata", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('user', 'runtime', 'system')",
            name=op.f("ck_work_item_events_actor_type"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["iam.users.id"],
            name=op.f("fk_work_item_events_actor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "work_item_id"],
            ["engagement.work_items.workspace_id", "engagement.work_items.id"],
            name=op.f("fk_work_item_events_workspace_id_work_item_id_work_items"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_work_item_events_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_item_events")),
        schema="engagement",
    )
    op.create_index(
        op.f("ix_work_item_events_workspace_id_work_item_id_occurred_at"),
        "work_item_events",
        ["workspace_id", "work_item_id", "occurred_at"],
        unique=False,
        schema="engagement",
    )
    # ### end Alembic commands ###

    for table in (*EDITABLE, *APPEND_ONLY):
        op.execute(_policies(table))
    op.execute(PARTITIONS)


def downgrade() -> None:
    raise RuntimeError("Migrations are forward-only; ship a new revision instead.")
