"""Agent releases: immutable, digest-checked snapshots per agent (step 4a).

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-28 23:48:35.215152
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Hand-written (not autogenerated). Frozen here: never import application code.
_IN_WORKSPACE = "workspace_id = tenancy.current_workspace_id()"
POLICIES = f"""
ALTER TABLE releases.agent_releases ENABLE ROW LEVEL SECURITY;
ALTER TABLE releases.agent_releases FORCE ROW LEVEL SECURITY;
CREATE POLICY agent_releases_read ON releases.agent_releases FOR SELECT USING ({_IN_WORKSPACE});
CREATE POLICY agent_releases_create ON releases.agent_releases
    FOR INSERT WITH CHECK ({_IN_WORKSPACE});
CREATE POLICY agent_releases_update ON releases.agent_releases FOR UPDATE
    USING ({_IN_WORKSPACE}) WITH CHECK ({_IN_WORKSPACE});
"""
# A release never changes after it is stored: only its status moves forward
# (published -> superseded | archived, superseded -> archived). Releases are never deleted.
IMMUTABLE = """
CREATE FUNCTION releases.guard_agent_release() RETURNS trigger
LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'agent releases are never deleted' USING ERRCODE = '42501';
    END IF;
    IF (pg_catalog.to_jsonb(NEW) - 'status') IS DISTINCT FROM (pg_catalog.to_jsonb(OLD) - 'status')
    THEN
        RAISE EXCEPTION 'agent releases are immutable' USING ERRCODE = '42501';
    END IF;
    IF NEW.status <> OLD.status AND NOT (
        (OLD.status = 'published' AND NEW.status IN ('superseded', 'archived'))
        OR (OLD.status = 'superseded' AND NEW.status = 'archived')
    ) THEN
        RAISE EXCEPTION 'invalid release status change' USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER agent_releases_immutable BEFORE UPDATE OR DELETE ON releases.agent_releases
    FOR EACH ROW EXECUTE FUNCTION releases.guard_agent_release();
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_releases",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("pack_key", sa.Text(), nullable=False),
        sa.Column("pack_version", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("digest", sa.Text(), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_release_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("published_by", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "digest ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_agent_releases_digest_format")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(snapshot) = 'object'", name=op.f("ck_agent_releases_snapshot_object")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'superseded', 'archived')",
            name=op.f("ck_agent_releases_status"),
        ),
        sa.CheckConstraint("version_no >= 1", name=op.f("ck_agent_releases_version_no")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["iam.users.id"], name=op.f("fk_agent_releases_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["published_by"], ["iam.users.id"], name=op.f("fk_agent_releases_published_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "agent_id"],
            ["agents.agents.workspace_id", "agents.agents.id"],
            name=op.f("fk_agent_releases_workspace_id_agent_id_agents"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "source_release_id"],
            ["releases.agent_releases.workspace_id", "releases.agent_releases.id"],
            name=op.f("fk_agent_releases_workspace_id_source_release_id_agent_releases"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["tenancy.workspaces.id"],
            name=op.f("fk_agent_releases_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_releases")),
        sa.UniqueConstraint(
            "agent_id", "version_no", name=op.f("uq_agent_releases_agent_id_version_no")
        ),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_agent_releases_workspace_id_id")),
        schema="releases",
    )
    op.create_index(
        op.f("ix_agent_releases_agent_id_created_at_id"),
        "agent_releases",
        ["agent_id", "created_at", "id"],
        unique=False,
        schema="releases",
    )
    op.create_index(
        "uq_agent_releases_one_published",
        "agent_releases",
        ["agent_id"],
        unique=True,
        schema="releases",
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_foreign_key(
        op.f("fk_conversations_workspace_id_agent_release_id_agent_releases"),
        "conversations",
        "agent_releases",
        ["workspace_id", "agent_release_id"],
        ["workspace_id", "id"],
        source_schema="engagement",
        referent_schema="releases",
    )
    # ### end Alembic commands ###
    op.execute(POLICIES)
    op.execute(IMMUTABLE)


def downgrade() -> None:
    raise RuntimeError("Migrations are forward-only; ship a new revision instead.")
