"""Caller interactions: contacts, consents, conversations and work items.

Public interface for other modules and entrypoints.
"""

from typing import TYPE_CHECKING

from praxima.shared.lazy import lazy_exports

if TYPE_CHECKING:  # real imports for type checkers; loaded lazily at runtime
    from praxima.modules.engagement.application.selectors import (
        CallEventView,
        ContactView,
        ConversationView,
        TaskView,
        WorkItemEventView,
        WorkItemKindView,
        WorkItemView,
        contacts_page,
        conversations_page,
        find_contact_by_phone,
        get_contact,
        get_conversation,
        get_task,
        get_work_item,
        tasks_page,
        work_item_kinds,
        work_items_page,
    )
    from praxima.modules.engagement.application.services import (
        ContactDraft,
        RevealedContact,
        RevealedWorkItem,
        WorkItemChanges,
        WorkItemDraft,
        assign_work_item,
        create_contact,
        create_task,
        create_work_item,
        erase_contact,
        erase_work_item,
        install_work_item_kinds,
        move_work_item,
        record_consent,
        reveal_contact,
        reveal_work_item,
        set_task_status,
        update_work_item,
    )
    from praxima.modules.engagement.application.vault import (
        Vault,
    )

_EXPORTS = {
    "CallEventView": "praxima.modules.engagement.application.selectors",
    "ContactView": "praxima.modules.engagement.application.selectors",
    "ConversationView": "praxima.modules.engagement.application.selectors",
    "TaskView": "praxima.modules.engagement.application.selectors",
    "WorkItemEventView": "praxima.modules.engagement.application.selectors",
    "WorkItemKindView": "praxima.modules.engagement.application.selectors",
    "WorkItemView": "praxima.modules.engagement.application.selectors",
    "contacts_page": "praxima.modules.engagement.application.selectors",
    "conversations_page": "praxima.modules.engagement.application.selectors",
    "find_contact_by_phone": "praxima.modules.engagement.application.selectors",
    "get_contact": "praxima.modules.engagement.application.selectors",
    "get_conversation": "praxima.modules.engagement.application.selectors",
    "get_task": "praxima.modules.engagement.application.selectors",
    "get_work_item": "praxima.modules.engagement.application.selectors",
    "tasks_page": "praxima.modules.engagement.application.selectors",
    "work_item_kinds": "praxima.modules.engagement.application.selectors",
    "work_items_page": "praxima.modules.engagement.application.selectors",
    "ContactDraft": "praxima.modules.engagement.application.services",
    "RevealedContact": "praxima.modules.engagement.application.services",
    "RevealedWorkItem": "praxima.modules.engagement.application.services",
    "WorkItemChanges": "praxima.modules.engagement.application.services",
    "WorkItemDraft": "praxima.modules.engagement.application.services",
    "assign_work_item": "praxima.modules.engagement.application.services",
    "create_contact": "praxima.modules.engagement.application.services",
    "create_task": "praxima.modules.engagement.application.services",
    "create_work_item": "praxima.modules.engagement.application.services",
    "erase_contact": "praxima.modules.engagement.application.services",
    "erase_work_item": "praxima.modules.engagement.application.services",
    "install_work_item_kinds": "praxima.modules.engagement.application.services",
    "move_work_item": "praxima.modules.engagement.application.services",
    "record_consent": "praxima.modules.engagement.application.services",
    "reveal_contact": "praxima.modules.engagement.application.services",
    "reveal_work_item": "praxima.modules.engagement.application.services",
    "set_task_status": "praxima.modules.engagement.application.services",
    "update_work_item": "praxima.modules.engagement.application.services",
    "Vault": "praxima.modules.engagement.application.vault",
}
__getattr__, __dir__ = lazy_exports(__name__, _EXPORTS)
__all__ = [
    "CallEventView",
    "ContactDraft",
    "ContactView",
    "ConversationView",
    "RevealedContact",
    "RevealedWorkItem",
    "TaskView",
    "Vault",
    "WorkItemChanges",
    "WorkItemDraft",
    "WorkItemEventView",
    "WorkItemKindView",
    "WorkItemView",
    "assign_work_item",
    "contacts_page",
    "conversations_page",
    "create_contact",
    "create_task",
    "create_work_item",
    "erase_contact",
    "erase_work_item",
    "find_contact_by_phone",
    "get_contact",
    "get_conversation",
    "get_task",
    "get_work_item",
    "install_work_item_kinds",
    "move_work_item",
    "record_consent",
    "reveal_contact",
    "reveal_work_item",
    "set_task_status",
    "tasks_page",
    "update_work_item",
    "work_item_kinds",
    "work_items_page",
]
